Add ECG demo (cardiac coherence using LF/HF)
timeflux/demos pull request #5
Opened 2022-09-20 15:24 UTC by bertrandlalo

2022-10-02 13:05 UTC, mesca requested changes
The cardiac features are lagging behind in the UI. Is this because of the filtering. Because of the graph rate?

2022-10-02 13:05 UTC, mesca commented on coherence/main.yaml
> +          ecg_cardiac: www  # now open http://localhost:8000/ecg_cardiac/
Rename route to `coherence`

2022-10-02 13:05 UTC, mesca commented on coherence/www/assets/app.css
> +    height: 500pt;  /* todo: unhardcode this height */
Indeed ;)

2022-10-02 13:05 UTC, mesca commented on coherence/www/assets/app.css
> +    /*#transition: background-color 2s ease-in-out;*/
Remove

2022-10-02 13:05 UTC, mesca commented on coherence/www/assets/app.js
> +function resize() {
This should be achievable with CSS only.

2022-10-02 13:05 UTC, mesca commented on coherence/README.md
> +	timeflux -d graphs/ecg_cardiac.yaml
Update graph name

2022-10-02 13:05 UTC, mesca commented on coherence/README.md
> +/!\ If you revert the IN+ (red) and IN-(black) electrodes, the ECG QRS will be inverted and the cardiac peaks won't be estimated correctly.
Use emoji instead: :warning:

2022-10-02 13:05 UTC, mesca commented on coherence/www/assets/app.js
> +const _gradientColors = [
Would be great to report the colors in the README or at least to provide a succinct explanation

2022-10-02 14:42 UTC, mesca requested changes

2022-10-02 14:42 UTC, mesca commented on coherence/main.yaml
> +  # - graphs/replay.yaml # uncomment this line to run on replayed data
Default should be sine so one can launch the demo without any hardware

2022-10-02 14:42 UTC, mesca commented on coherence/www/assets/app.js
> +const columns = ["bpm", "lf", "hf", "lf/hf"]; // columns of EMG activation bursts
EMG ?
;)

2022-10-02 14:42 UTC, mesca commented on coherence/www/assets/app.js
> +    const px = value * (max - min) + min + "px"; // Transform to pixels
Use percentage?

2022-10-02 15:08 UTC, mesca requested changes

2022-10-02 15:08 UTC, mesca commented on coherence/www/assets/app.js
> +const color_gradient = (x) => {
Harmonize function declaration style

2022-10-02 15:08 UTC, mesca commented on coherence/main.yaml
> +          circle:
Use the route name

2022-10-02 15:08 UTC, mesca commented on coherence/nodes/cardiac.py
> +class CardiacFreqMarkers(Node):
Comment inputs and output

2022-10-02 15:08 UTC, mesca commented on coherence/nodes/events.py
> +class ToSignal(Node):
Give a more explicit name? `EventToSignal`?

2022-10-02 15:08 UTC, mesca commented on coherence/nodes/events.py
> +    Attributes:
Add line breaks to make it more readable

2022-10-02 15:08 UTC, mesca commented on coherence/nodes/events.py
> +        super().__init__()
Why this line?

2022-10-07 09:30 UTC, bertrandlalo commented on coherence/www/assets/app.js
> +function resize() {
Tell me how 🙏😇

2022-10-07 09:39 UTC, bertrandlalo commented on coherence/www/assets/app.js
> +    const px = value * (max - min) + min + "px"; // Transform to pixels
?

2022-10-13 13:48 UTC, mesca commented on coherence/www/assets/app.js
> +function resize() {
You could probably use CSS percentage and simplify the code.

2022-10-13 13:49 UTC, mesca commented on coherence/www/assets/app.js
> +const _gradientColors = [
Great. I would avoid mentioning Gandhi though (here and in the code).

2022-10-15 17:00 UTC, merged